{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mcp-openshift.namespace" . }}
  labels:
    {{- include "mcp-openshift.labels" . | nindent 4 }}
{{- end }}
