{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-openshift.serviceAccountName" . }}
  namespace: {{ include "mcp-openshift.namespace" . }}
  labels:
    {{- include "mcp-openshift.labels" . | nindent 4 }}
{{- end }}
